### PR TITLE
Setup pre-commit

### PR DESCRIPTION
**Pull request by atztogo**
Most of lines were mechanically modified by tools. I explain about those I did by using my hands below.

As we discussed at issue #31, I set up pre-commit. Tests passed. It was a bit more tough job than I expected, at least. There are still a few failures in pylint, which I would like @espenfl to fix (see below.) Most of complaints were reasonable and I followed them. I wish I didn't break the logic. Some complaints were reasonable, but when I wanted to follow the original code, I used `# pylint: disable=...`. So if you are interested in those, please grep `pylint: #disable`.

Three new files: `.pre-commit-config.yaml`, `.style.yapf`, `pyproject.toml`. For settings of these files, I finally referred aiida-quantumespresso. I wanted to respect pydocstyle (now commented out in `.pre-commit-config.yaml`), but it was postponed. I excluded `tests` directory from pylint check. I want to include it in the future when I feel my life is easy. Or if somebody else works on it, my life becomes easy.

One important note that I must tell is that I moved the function `parsevasp.utils.file_handler` to in `parsevasp.base.open_close_file_handler` (with renamed). Two independent reasons:
1. Solving circular import
2. The function name should be different from argument name of itself.

The following is the output of pre-commit run.
```
% pre-commit run --all-files
Fix double quoted strings................................................Passed
Fix End of Files.........................................................Passed
Fix python encoding pragma...............................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
isort....................................................................Passed
flynt....................................................................Passed
yapf.....................................................................Passed
pylint...................................................................Failed
- hook id: pylint
- exit code: 6

************* Module parsevasp.vasprun
parsevasp/vasprun.py:1960:2: W0511: TODO: check in the future if it is faster to fetch all scstep (fixme)
parsevasp/vasprun.py:111:51: E1101: Instance of 'Xml' has no 'ERROR_ONLY_ONE_ARGUMENT' member (no-member)
parsevasp/vasprun.py:112:21: E1101: Instance of 'Xml' has no 'ERROR_ONLY_ONE_ARGUMENT' member (no-member)
parsevasp/vasprun.py:2382:21: E1101: Instance of 'Xml' has no 'ERROR_NO_NBADS' member; maybe 'ERROR_NO_NBANDS'? (no-member)
parsevasp/vasprun.py:3579:51: E1101: Instance of 'Xml' has no 'ERROR_ONLY_ONE_ARGUMENT' member (no-member)
************* Module parsevasp.kpoints
parsevasp/kpoints.py:102:51: E1101: Instance of 'Kpoints' has no 'USE_ONE_ARGUMENT' member (no-member)
parsevasp/kpoints.py:103:21: E1101: Instance of 'Kpoints' has no 'USE_ONE_ARGUMENT' member (no-member)
parsevasp/kpoints.py:109:51: E1101: Instance of 'Kpoints' has no 'USE_ONE_ARGUMENT' member (no-member)
parsevasp/kpoints.py:110:21: E1101: Instance of 'Kpoints' has no 'USE_ONE_ARGUMENT' member (no-member)
parsevasp/kpoints.py:220:71: E1101: Instance of 'Kpoints' has no 'ERROR_TETRA_CON_FIVE' member (no-member)
parsevasp/kpoints.py:221:41: E1101: Instance of 'Kpoints' has no 'ERROR_TETRA_CON_FIVE' member (no-member)
```

### CODE REVIEW

**Comment by atztogo** [comment]
@espenfl, do we need files under the `ops` directory?

**Comment by espenfl** [comment]
> @espenfl, do we need files under the ops directory?

@atztogo We do not need the `run_coverals` but the `update_versions` is nice when making a release so I would like to keep that.

**Comment by atztogo** [comment]
I see. Then I would like to remind the following.

pylint complained about `subprocess32` module. I just changed the module name to `subprocess` in the file though I didn't exactly understand it. So if it causes the problem, please fix it.

https://github.com/aiida-vasp/parsevasp/blob/c16cee80a08cfcdc4fa0fd30633ece750f541243/ops/update_version.py#L7

**Comment by espenfl** [comment]
@atztogo Great. Thanks for adding. Also see our `pre-commit` config in `aiida-vasp`. Maybe we should try to make them pretty similar between `aiida-vasp` and `parsevasp`. Happy to do updates on the `aiida-vasp` side as well. Maybe we can add the `yaml` linter check to `parsevasp` as well? Also, check for large files and forbid submodules are nice, even though never strictly necessary.

**Comment by espenfl** [comment]
> So if it causes the problem, please fix it.

Thanks for taking care of this. No, this is not an issue at all and just related to Python 2 compatibility, which is now not a concern anymore.

**Comment by atztogo** [comment]
Sure, but to be careful that some of them can be a full one day job, it is good after merging as another PR. And not altogether, but introducing one feature by one feature may be good for our mental health :P 

I also recommend registering https://pre-commit.ci/.

**Comment by espenfl** [comment]
@atztogo I pushed a commit with the necessary updates. In the process I also took the liberty to convert the config to a two space indentation format and added the `yaml`, `rst`, big files and no submodules modules as we have in the `aiida-vasp` config. Thanks a lot for fixing this.

**Comment by atztogo** [comment]
Thank you @espenfl. For me it looks good!

**Comment by atztogo** [comment]
Thanks @espenfl for your quick review and merge!

**Pull request merged**
