### PR TITLE
doscar.py reads the pdos incorrectly

### PR DESCRIPTION
**Pull request by adair-nicolson**
The pdos for each ion is set to the pdos of the first ion in the DOSCAR

https://github.com/aiida-vasp/parsevasp/blob/db19067dac597a477d52691b4f8aecdd3d31e1f3/parsevasp/doscar.py#L220-L223

I think this is the source of the error. During the for loop the pdos of the first ion in the `DOSCAR` is read in for each ion. I have a fix, but I don't know if it is the most elegant solution.

```
if line_2 in data:
    start = data.index(line_2) + 1
        for _ in range(num_ions):
            pdos_items += [data[start:start + ndos]]
            start += (ndos+1)
```

### CODE REVIEW

**Comment by zhubonan** [comment]
Looks good to me.  I guess this has gone unnoticed because in the test DOSCAR only contains one atom.... @espenfl

**Comment by espenfl** [comment]
@adair-nicolson Thanks a lot for detecting and submitting this fix. I agree with @zhubonan.

**Comment by espenfl** [comment]
@adair-nicolson Can you also update the test that fail? Let me know if you need some help with it.

**Comment by zhubonan** [comment]
@espenfl I think this is ready to go now!

**Comment by espenfl** [comment]
@adair-nicolson Thanks a lot. Merged. Sorry for the delay.

**Pull request merged**
